### PR TITLE
Move caching into separate class

### PR DESCRIPTION
**Pull request by yiiliveext**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️

### CODE REVIEW

**Comment by xepozz** [comment]
Would be great to use https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php

**Comment by xepozz** [comment]
Related to https://github.com/yiisoft/router-fastroute/issues/8

**Comment by yiiliveext** [comment]
> Would be great to use https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php

It's a bad idea, will be not compatible with Yiisoft\CacheInterface that extends Psr\SimpleCache\CacheInterface

**Comment by xepozz** [comment]
we can add one more package, that will implement `psr/cache`

**Comment by xepozz** [comment]
I think comatibility with PSR is more priority that compatibility with Yiisoft/* packages

**Comment by yiiliveext** [comment]
> I think comatibility with PSR is more priority that compatibility with Yiisoft/* packages

Psr\SimpleCache\CacheInterface is not PSR???

**Comment by xepozz** [comment]
`psr/cache` is better than `psr/simple-cache`

**Comment by terabytesoftw** [comment]
Because if the framework already has the implementation of Cache because it is not used, I think it is a bad idea not to use what already exists.

**Comment by yiiliveext** [comment]
> Because if the framework already has the implementation of Cache because it is not used, I think it is a bad idea not to use what already exists.

You can use the framework Cache implementation, why not? This PR just gives you this ability.

**Comment by terabytesoftw** [comment]
> > Because if the framework already has the implementation of Cache because it is not used, I think it is a bad idea not to use what already exists.
> 
> You can use the framework Cache implementation, why not? This PR just gives you this ability.

Excuse my bad English, my question would be because there is a cache implementation inside router-fastroute, it should not be implemented in a cache package, and if its implementation is good, can it be used by everyone?

**Comment by yiiliveext** [comment]
> 
> Excuse my bad English, my question would be because there is a cache implementation inside router-fastroute, it should not be implemented in a cache package, and if its implementation is good, can it be used by everyone?
The implementation inside router-fastroute is very specific and is suitable only for simple arrays (without objects and functions). If you want a universal implementation you have to do much more work. When someone creates such an implementation for the Cache package, we will remove the implementation from the router-fastroute package.

**Comment by samdark** [comment]
Good job 👍

**Pull request merged**
