### PR TITLE
Move configuration to web

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by yiiliveext** [comment]
It is needed for the console app

**Comment by samdark** [comment]
Won't be merged because, indeed, it's used in console as well.

**Comment by xepozz** [comment]
UrlMatcher shouldn't be used in console. It will be replaced with RouteCollector or any.

**Comment by yiiliveext** [comment]
> UrlMatcher shouldn't be used in console. It will be replaced with RouteCollector or any.

I'm working on this problem.

**Comment by samdark** [comment]
@xepozz, @yiiliveext let's re-do it when the root problem is fixed.

**Pull request closed without merging**
